name: StockPhotos
favicon: null
layout_spectrum: 0.0013130761217325926
typography_spectrum: 0.16849512187764049
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9368593993131071
  lightness: 0.5239019740838557
  saturation: 0.06290433718822896
  rhythmicContrast: 0.38828558358363807
purpose: []
